### ISSUE TITLE
No buttons works

### ISSUE THREAD

**Issue by sveinse** [sveinse/zaptec#15]
No buttons are working. It returns error similar to:

```
2023-09-16 21:25:32.397 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140128031067712] Running command 'stop_pause' failed
Traceback (most recent call last):
  File "/workspaces/ha-core/config/custom_components/zaptec/button.py", line 36, in async_press
    await self.zaptec_obj.command(self.key)
  File "/workspaces/ha-core/config/custom_components/zaptec/api.py", line 589, in command
    raise ValueError(f"Unknown command {command}")
ValueError: Unknown command stop_pause
```

Related to #2

**Comment by sveinse** [comment]
Fixed in release 80b934e. Closing issue
